#!/bin/bash
set -e

if [[ "$1" = *.c ]]
then
	out=${1%.c}.out
elif [[ "$1" = *.cc ]]
then
	out=${1%.cc}.out
	g++ -o $out $1 -lGL -lGLU -lglut -lm
else
	echo "File should have .c or .cc (for C++) extension"
	return 1
fi
./$out;

